Client:
  Input:
    KafKa:
      Broker:
        - {Host: "127.0.0.1", Port: "9092", User: "", Pwd: ""}
      MaxWaitTime: 3
      Topic:
        - "log"
      Group: "log_collector"
      Consumers: 1
  Output:
    ElasticSearch:
      Username: ""
      Password: ""
      Host: "127.0.0.1"
      Port: "9200"
      Index: "log"



